name: quizzique_functions
description: The server-side function for appwrite to use with the Quizzique app
version: 1.0.0

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  dart_appwrite: ^16.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
