name: Build and Deploy Flutter Web

on:
  workflow_dispatch:

permissions:
  contents: write  # Required for pushing to another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed so we can push to another branch

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # Change to your version
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Create dotenv file from secret
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > dotenv
        shell: bash

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true  # Ensures the branch only contains web files
